### ISSUE TITLE
RestFul api use

### ISSUE THREAD

**Issue by basitiyidir** [valohai/django-allauth-2fa#163] opened 2023-05-31 11:49 UTC
I can't use it with Django Rest Framework.

I'm try with POSTMAN. But I am not getting results

Is there a way to use it with DRF?

`AttributeError: 'CustomUser' object has no attribute 'otp_device'`

**Comment by valberg** [comment] 2023-06-12 20:32
Hi @basitiyidir

We need more information on this to assess if the issue is in the code or if it is an documentation issue.

I'm closing this for now, but do add more details and we can look at opening it again.

**Closed as completed by valberg** 2023-06-12 20:32 UTC
